language: rust
rust:
  - nightly

addons:
  apt:
    packages:
      - protobuf-compiler
      - libprotoc-dev
      - portaudio19-dev

script:
    - cargo build --no-default-features --verbose
    - cargo test --no-default-features --verbose
