[package]
name = "librespot-protocol"
version = "0.1.0"
authors = ["Paul Liétar <paul@lietar.net>"]
build = "build.rs"

[dependencies]
mod_path = "~0.1.6"
protobuf = "~1.0.10"

[build-dependencies.protobuf_build]
git = "https://github.com/plietar/rust-protobuf-build.git"
